changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: "### {{.Kind}}"
changeFormat: '- {{.Body}}{{- if not (eq .Custom.Issue "")}} ([#{{.Custom.Issue}}](https://github.com/luislavena/drift/issues/{{.Custom.Issue}})){{- end }}'
kinds:
  - label: Added
    key: added
    auto: minor
  - label: Improved
    key: improved
    auto: minor
  - label: Changed
    key: changed
    auto: major
  - label: Deprecated
    key: deprecated
    auto: minor
  - label: Removed
    key: removed
    auto: major
  - label: Fixed
    key: fixed
    auto: patch
  - label: Security
    key: security
    auto: patch
  - label: Internal
    key: internal
    auto: patch
custom:
  - key: Issue
    type: int
    minInt: 1
    optional: true
newlines:
  beforeChangelogVersion: 1
  afterKind: 1
  beforeKind: 1
  endOfVersion: 1
envPrefix: CHANGIE_
replacements:
  - path: "shard.yml"
    find: "^version: .*"
    replace: "version: {{.VersionNoPrefix}}"
