services:
  app:
    image: ghcr.io/luislavena/hydrofoil-crystal:${CRYSTAL_VERSION:-1.16}
    command: overmind start -f Procfile.dev
    working_dir: /workspace/${COMPOSE_PROJECT_NAME}
    depends_on:
      - postgres
    environment:
      # Workaround Overmind socket issues with Vite
      # Ref: https://github.com/luislavena/hydrofoil-crystal/issues/66
      - OVERMIND_SOCKET=/tmp/overmind.sock
      # Disable Shards' postinstall
      - SHARDS_OPTS=--skip-postinstall
      # Test DBs
      - POSTGRES_DB_URL=postgres://drift:drift@postgres:5432/drift_test

    # Set these env variables using `export FIXUID=$(id -u) FIXGID=$(id -g)`
    user: ${FIXUID:-1000}:${FIXGID:-1000}

    volumes:
      - .:/workspace/${COMPOSE_PROJECT_NAME}:cached

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: drift_test
      POSTGRES_USER: drift
      POSTGRES_PASSWORD: drift
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
    driver: local
