services:
  app:
    image: ghcr.io/luislavena/hydrofoil-crystal:${CRYSTAL_VERSION:-1.16}
    command: overmind start -f Procfile.dev
    working_dir: /app
    environment:
      # Workaround Overmind socket issues with Vite
      # Ref: https://github.com/luislavena/hydrofoil-crystal/issues/66
      - OVERMIND_SOCKET=/tmp/overmind.sock
      # Disable Shards' postinstall
      - SHARDS_OPTS=--skip-postinstall

    # Set these env variables using `export FIXUID=$(id -u) FIXGID=$(id -g)`
    user: ${FIXUID:-1000}:${FIXGID:-1000}

    volumes:
      - .:/app:cached
