name: Build Release Binaries

on:
  push:
    tags:
      # Supports only MAJOR.MINOR.PATCH versioning
      - "v[0-9]+.[0-9]+.[0-9]+"

# We must only run one release workflow at a time to prevent corrupting
# our release artifacts.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - x86_64-linux-musl
          - aarch64-linux-musl
          - aarch64-apple-darwin
    outputs:
      tag: ${{ steps.extract_version.outputs.tag }}
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/luislavena/hydrofoil-crystal:1.15
        with:
          args: sh -c "shards check || shards install --skip-postinstall --skip-executables"

      - name: Extract version
        id: extract_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Build for ${{ matrix.platform }}
        uses: docker://ghcr.io/luislavena/crystal-xbuild:tip
        with:
          entrypoint: xbuild
          args: src/cli.cr drift ${{ matrix.platform }}

      - name: Create tarball
        run: |
          tar -czf drift-${{ steps.extract_version.outputs.version }}-${{ matrix.platform }}.tar.gz -C build/${{ matrix.platform }} drift
          tar -tf drift-${{ steps.extract_version.outputs.version }}-${{ matrix.platform }}.tar.gz

      - name: Calculate SHA256
        run: |
          sha256sum drift-${{ steps.extract_version.outputs.version }}-${{ matrix.platform }}.tar.gz > sha-info-${{ matrix.platform }}.txt
          cat sha-info-${{ matrix.platform }}.txt

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_version.outputs.tag }}
          files: drift-${{ steps.extract_version.outputs.version }}-${{ matrix.platform }}.tar.gz

      - name: Upload SHA256 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sha-info-${{ matrix.platform }}
          path: sha-info-${{ matrix.platform }}.txt

  update-release-notes:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG: ${{ needs.build.outputs.tag }}
      VERSION: ${{ needs.build.outputs.version }}
    steps:
      - name: Download all SHA256 info files
        uses: actions/download-artifact@v4
        with:
          path: ./sha-info

      - name: Generate SHA256SUMS file and checksums list
        run: |
          touch SHA256SUMS
          echo "## Checksums" > checksums_list.md
          echo "" >> checksums_list.md
          echo '```' >> checksums_list.md

          # Process each SHA info file
          for info_dir in ./sha-info/sha-info-*; do
            cat $info_dir/* >> SHA256SUMS
            cat $info_dir/* >> checksums_list.md
          done

          echo '```' >> checksums_list.md

          cat SHA256SUMS
          cat checksums_list.md

      - name: Get current release body
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const tag = process.env.TAG;
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag
              });
              return release.data.body || '';
            } catch (error) {
              console.log('Error fetching release:', error);
              return '';
            }

      - name: Prepare combined release notes
        run: |
          echo '${{ steps.release.outputs.result }}' > combined_body.md
          echo '' >> combined_body.md
          cat checksums_list.md >> combined_body.md
          echo "---"
          cat combined_body.md

      - name: Update release with checksums
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          body_path: combined_body.md
          files: SHA256SUMS
