name: Create Release PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Batch changes
        uses: miniscruff/changie-action@v2
        with:
          args: batch auto

      - name: Merge changes
        uses: miniscruff/changie-action@v2
        with:
          args: merge

      - name: Get the latest version
        id: latest
        uses: miniscruff/changie-action@v2
        with:
          args: latest

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Release ${{ steps.latest.outputs.output }}
          branch: release/${{ steps.latest.outputs.output }}
          commit-message: Release ${{ steps.latest.outputs.output }}
