name: Test

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "shard.*"
      - "spec/**"
      - "src/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "shard.*"
      - "spec/**"
      - "src/**"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: crystal tool format --check

  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-ameba/github-action@v0.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: shards install --skip-executables --skip-postinstall
      - run: crystal spec
