name: Test

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "shard.*"
      - "spec/**"
      - "src/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "shard.*"
      - "spec/**"
      - "src/**"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: crystal tool format --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: shards install
      - run: crystal spec
